schema:
  format:
    openapi: '3.0.0'
  environment_input_type: 'EnvironmentInput'
  types:
    EnvironmentInput:
      type: object
      description: 'Input properties for eks environment.'
      required:
        - cluster_name
        - vpc_cidr
        - iam_platform_user
        - eks_admin_role_name
        - eks_cluster_domain
        - acm_certificate_domain
        - kubernetes_version
        - addon_repo_url
        - workload_repo_url
        - workload_repo_path
      properties:
        cluster_name:
          title: 'Cluster name'
          type: string
          default: 'demo1'

        vpc_cidr:
          title: 'VPC CIDR'
          type: string
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: '10.0.0.0/16'
        iam_platform_user:
          title: 'iam_platform_user'
          type: string
          description: 'Additional IAM role to be admin in the cluster'
          default: 'platform-user'
        eks_admin_role_name:
          title: 'EKS Admin Additional Role Name'
          type: string
          description: 'IAM Role for cluster access'
          default: 'demo3'
        eks_cluster_domain:
          title: 'Route53 domain'
          type: string
          description: 'Domain name for route53 Hostedzone'
          default: 'demo.eks.demo3.allamand.com'
        acm_certificate_domain:
          title: 'Certificat Manager domain'
          type: string
          description: 'nom de domaine pour le certificat dans Certificat Manager'
          default: '*.demo.eks.demo3.allamand.com'

        addon_repo_url:
          title: 'GitHub Addons repo'
          type: string
          description: 'GitHub Repo for managing Kuberbetes Addons'
          default: 'https://github.com/seb-demo/eks-blueprints-add-ons.git'

        workload_repo_url:
          title: 'GitHub ArgoCD Workloads repo'
          type: string
          description: 'GitHub Repo for managing Kuberbetes ArgoCD Workloads'
          default: 'https://github.com/seb-demo/eks-blueprints-workloads.git'

        workload_repo_path:
          title: 'GitHub ArgoCD Workloads repo path'
          type: string
          description: 'GitHub path in the Repo for managing Kuberbetes ArgoCD Workloads'
          default: 'envs/dev'

        kubernetes_version:
          title: 'Kubernetes version'
          type: string
          enum: ['1.21']
          default: '1.21'
        aws_load_balancer_controller:
          title: 'Enable AWS Load Balancer Controller Add-On'
          type: boolean
          default: true
        metrics_server:
          title: 'Enable Metrics Server Add-On'
          type: boolean
          default: true
        aws_for_fluentbit:
          title: 'Enable AWS for FluentBit Add-On'
          type: boolean
          default: true
        cert_manager:
          title: 'Enable Cert Manager Add-On'
          type: boolean
          default: true
        vpa:
          title: 'Enable VPA Add-On'
          type: boolean
          default: true
        karpenter:
          title: 'Enable Karpenter Add-On'
          type: boolean
          default: true
        external_dns:
          title: 'Enable External DNS'
          type: boolean
          default: true
