

format:
	terraform fmt	cd templates/eks-blueprint-terraform-workshop/v4/infrastructure && terraform fmt

check:
	cd templates/eks-blueprint-terraform-workshop/v4/infrastructure && terraform fmt -diff -check