schema:
  format:
    openapi: '3.0.0'
  environment_input_type: 'EnvironmentInput'
  types:
    EnvironmentInput:
      type: object
      description: 'Input properties for eks environment.'
      required:
        - core_stack_name
        - vpc_cidr
        - argocd_secret_manager_name_suffix
        - hosted_zone_name
      properties:
        core_stack_name:
          title: 'Core stack name'
          type: string
          default: 'proton'
        vpc_cidr:
          title: 'VPC CIDR'
          type: string
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: '10.0.0.0/16'
        argocd_secret_manager_name_suffix:
          title: 'ArgoCD Secret Name Suffix'
          type: string
          description: 'Suffix for ArgoCD secret name'
          default: 'argocd-admin-secret'
        hosted_zone_name:
          title: 'Route53 domain'
          type: string
          description: 'Domain name for route53 Hostedzone'
          default: 'sallaman.people.aws.dev'
