schema:
  format:
    openapi: '3.0.0'
  environment_input_type: 'EnvironmentInput'
  types:
    EnvironmentInput:
      type: object
      description: 'Input properties for eks environment.'
      required:
        - aws_region
        - vpc_cidr
        - argocd_secret_manager_name_suffix
        - hosted_zone_name
        - tf_state_bucket
        - tf_state_bucket_region
      properties:
        aws_region:
          title: AWS Region
          type: string
          description: AWS Region where resources will reside
          default: eu-west-1
        vpc_cidr:
          title: 'VPC CIDR'
          type: string
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: '10.0.0.0/16'
        argocd_secret_manager_name_suffix:
          title: 'ArgoCD Secret Name Suffix'
          type: string
          description: 'Suffix for ArgoCD secret name'
          default: 'argocd-admin-secret'
        hosted_zone_name:
          title: 'Route53 domain'
          type: string
          description: 'Domain name for route53 Hostedzone'
          default: 'sallaman.people.aws.dev'
        tf_state_bucket:
          title: Terraform state storage S3 bucket
          type: string
          description: S3 Bucket to store Terraform state
          default: aws-proton-terraform-bucket-382076407153
        tf_state_bucket_region:
          title: State bucket AWS Region
          type: string
          description: AWS Region where state bucket resides
          default: eu-west-1